### ISSUE TITLE
Unable to run newer commits

### ISSUE THREAD

**Issue by markdesouza** [repleo/bounca#12]
Hi,

I noticed that the docker container for the project was rather old so I started on the task of updating it to run with the current stable version of Debian (8->10) and also the latest commit of bounca (v0.1.0 to HEAD). 
However I notice that in recent commits, whilst I am able to get the application to run, it does not create a root certificate files. It only creates the db entries and the "root" directory in pki directory. As such the root certificate is unable to be viewed (blank dialog shown) or downloaded (file not found) and an intermediate certificate can not be produced.

The last commit that works is 161228df5c87f36cbd1c805df09ab8daf0b3e3e6  "flake8 errors" and assume that the commit "Added factories for core models" causes the files to not be produced correctly.

Kind Regards,
Mark

**Comment by bjarnoldus** [comment]
A new version of bounca can be found on www.bounca.org, with the link to gitlab
