### ISSUE TITLE
TemplateSyntaxError: 'staticfiles' is not a registered tag library.

### ISSUE THREAD

**Issue by diddi-** [repleo/bounca#18]
I've followed the manual [getting started guide](https://www.bounca.org/getting_started.html) as well as the README but when I try to access the website I get this error

```
TemplateSyntaxError at /
'staticfiles' is not a registered tag library. Must be one of:
account
admin_list
admin_modify
admin_urls
cache
countries
djng_tags
grp_tags
i18n
l10n
log
rest_framework
static
tz
version_tags
```

I've installed the OS packages and everything from `requirements.txt`, is there something else I'm missing?

**Comment by bjarnoldus** [comment]
Hi Diddi,

I'm refactoring the application, this will takes some months to finish. Maybe you can fix it by adding the staticfiles tag.

Jeroen

**Comment by Peter2121** [comment]
Any news on this?

**Comment by bjarnoldus** [comment]
Yes, I'm working on a complete rebuild of the tool. https://gitlab.com/bounca/bounca, will also be pushed to this repo. staticfiles has been removed in a newer django release. might be easy to fix.

**Comment by Peter2121** [comment]
@bjarnoldus yes, staticfiles is not a great problem, I've fixed it. But there are many other problems preventing the app to work correctly (login & registration does not work). Hope you'll fix it soon, I'm waiting for this ;)
What repository will be the primary one for this project - Github or Gitlab?

**Comment by bjarnoldus** [comment]
Currently gitlab, but i will publish/push the repo also to github. The new version is a complete rebuild The engine is now python based instead of filesystem based, and wrote more integration/unit tests. I'm working on the UI now.

**Comment by Peter2121** [comment]
Thanks for your efforts!

**Comment by bjarnoldus** [comment]
A new version of bounca can be found on www.bounca.org, with the link to gitlab
