### ISSUE TITLE
Use with external RootCa

### ISSUE THREAD

**Issue by markush97** [repleo/bounca#23]
As you stated in the documentary, it is recommended to keep the rootCA key offline. Thus I don´t like the need I have to create it via the webinterface itself. I would like to create the rootCA manually via openSSL, then create an intermediate pair and import this pair into the webinterface. Isn´t there any way to achieve this?

Is this project even alive anymore?

**Comment by markush97** [comment]
May I help you? I would really like to participate in your project, since I am looking for a good CA solution for a long time now.

**Comment by bjarnoldus** [comment]
Yes, though it is still too immature to split work. https://gitlab.com/bounca/bounca
but lets stay in contact when I finished the frontend, and basis features

**Comment by bjarnoldus** [comment]
Hi Markus,

I've finally released a new version. I think you can use the intermedia ca by just replacing the keys in the db of the new version. In the future an import functionality would be cool
