### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by realRaghavGupta** [repleo/bounca#4]
Always get the following error:

**TASK [repleo.bounca : Install bounca requirements] *****************************
fatal: [**.***.**.**]: FAILED! => {"changed": false, "cmd": "/usr/bin/pip2 freeze", "failed": true, "msg": "\n:stderr: Traceback (most recent call last):\n  File \"/usr/bin/pip2\", line 9, in <module>\n    load_entry_point('pip==1.5.6', 'console_scripts', 'pip2')()\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources.py\", line 356, in load_entry_point\n    return get_distribution(dist).load_entry_point(group, name)\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources.py\", line 2476, in load_entry_point\n    return ep.load()\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources.py\", line 2190, in load\n    ['__name__'])\n  File \"/usr/lib/python2.7/dist-packages/pip/__init__.py\", line 74, in <module>\n    from pip.vcs import git, mercurial, subversion, bazaar  # noqa\n  File \"/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py\", line 9, in <module>\n    from pip.download import path_to_url\n  File \"/usr/lib/python2.7/dist-packages/pip/download.py\", line 25, in <module>\n    from requests.compat import IncompleteRead\nImportError: cannot import name IncompleteRead\n"}

RUNNING HANDLER [repleo.nginx : reload nginx] **********************************
	to retry, use: --limit @#######/install-bounca.retry

PLAY RECAP *********************************************************************
**.***.**.**              : ok=29   changed=22   unreachable=0    failed=1**   

Trying on fresh debian jessie VPS. always get the same error

**Comment by bjarnoldus** [comment]
A new version of bounca can be found on www.bounca.org, with the link to gitlab
