### ISSUE TITLE
No valid certificate for website https://bounca.org/

### ISSUE THREAD

**Issue by e-alfred** [repleo/bounca#6]
Hello,

please get a new certificate for https://bounca.org/ because StarSSL certificates are untrusted by most browsers now and I do not think that it is a good idea for a page about certificates to run on an untrusted one.

More here:

https://security.googleblog.com/2016/10/distrusting-wosign-and-startcom.html
https://blog.mozilla.org/security/2016/10/24/distrusting-new-wosign-and-startcom-certificates/

**Comment by bjarnoldus** [comment]
Fixed, thanks :-)
