### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by stathis** [repleo/bounca#7]
Is it completely dead?

**Comment by bjarnoldus** [comment]
Hi, It is on hold. I need to find time to update it and fix bugs. I still use the project to create my own keys

**Comment by stathis** [comment]
Whenever you've got time it'd be great if you looked into this issue:
[https://github.com/repleo/bounca/issues/5](url)

**Comment by bjarnoldus** [comment]
I've answered the issue: it might be this bug: https://stackoverflow.com/questions/94445/using-openssl-what-does-unable-to-write-random-state-mean

**Comment by reddec** [comment]
Hi all! Sorry, I really didn't know about this project when I started my own - [ssl-cp](https://github.com/reddec/ssl-cp). Many ideas are very similar.
Maybe my project will help someone.

And pull-requests are always welcome!

**Comment by bjarnoldus** [comment]
I'm currently updating this project, rebuilding some core components to make it more robust and add automatic testing.
